project_id = "nmeyylvltlvvcvbhvxpz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.bootstrap-admin]
    verify_jwt = false
  [functions.notification-alertes]
    verify_jwt = false
  [functions.notification-validation]
    verify_jwt = false
  [functions.confirm-login-device]
    verify_jwt = false
  [functions.check-login-device]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
