// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Renvoie le texte fourni tel quel. Utile pour v\xE9rifier la connectivit\xE9 au serveur MCP.",
  inputSchema: { text: z.string().min(1).describe("Texte \xE0 renvoyer.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ebene-services-mcp",
  title: "EBENE SERVICES MCP",
  version: "0.1.0",
  instructions: "Outils MCP pour l'application EBENE SERVICES. Utilisez `echo` pour v\xE9rifier la connectivit\xE9.",
  tools: [echo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
