ALTER TABLE public.societe_config
  ADD COLUMN IF NOT EXISTS format_facture TEXT NOT NULL DEFAULT 'FAC-{YYYY}-{NNN}',
  ADD COLUMN IF NOT EXISTS format_devis   TEXT NOT NULL DEFAULT 'DEV-{YYYY}-{NNN}',
  ADD COLUMN IF NOT EXISTS compteur_facture INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS compteur_devis   INTEGER NOT NULL DEFAULT 1;