directories:
  output: dist-electron
  buildResources: public/icons
appId: com.ebeneservices.app
productName: EBENE SERVICES
copyright: © EBENE SERVICES
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - public/icons/**/*
      - package.json
asar: true
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icons/icon.ico
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: EBENE SERVICES
  installerIcon: public/icons/icon.ico
  uninstallerIcon: public/icons/icon.ico
  deleteAppDataOnUninstall: false
publish:
  - provider: github
    owner: Ennod22
    repo: ebenes
electronVersion: 41.3.0
